language: node_js
node_js:
  - "10.4.1"
sudo: true

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng test --watch false --browsers ChromeHeadless
  - ng e2e
  - yarn build --prod --base-href $base_href #base_href should be given in travis as an environment variable
